---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker container
      docker_container:
        name: insurance-app
        image: vigneshwar1908/insure-me:v2
        state: started
        ports:
          - "8081:8081"
